# Generated by Django 3.1.7 on 2021-03-07 14:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tamrin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='exercise')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to='videos')),
            ],
        ),
        migrations.CreateModel(
            name='Javab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('file', models.FileField(upload_to='tamrin')),
                ('deadline', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 7, 14, 16, 24, 910107))),
                ('vote', models.IntegerField(default=100)),
                ('tamrin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.tamrin')),
            ],
        ),
    ]
