# Generated by Django 3.1.7 on 2021-03-07 18:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='javab',
            name='deadline',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 7, 18, 51, 18, 797882)),
        ),
        migrations.AlterField(
            model_name='tamrin',
            name='file',
            field=models.FileField(upload_to='tamrin'),
        ),
    ]
